com.example.choturemote.MyBluetoothService.ConnectThread Class Reference
Client thread that initiates a Bluetooth connection.
Public Member Functions
ConnectThread (BluetoothDevice device, UUID uuid)
Public constructor for the ConnectThread class.
void run ()
Main code that runs in the Thread.
void cancel ()
Closes the socket.
Private Attributes
final BluetoothSocket mmSocket
An instance of a Bluetooth socket.
Detailed Description
Client thread that initiates a Bluetooth connection.
A Bluetooth client sends the connection request and the Bluetooth Server component accepts the request.
A thread is a thread of execution in a program. The Java Virtual Machine allows an application to have multiple threads of execution running concurrently.
This one creates a BluetoothSocket
Definition at line 141 of file MyBluetoothService.java.
Constructor & Destructor Documentation
ConnectThread()
com.example.choturemote.MyBluetoothService.ConnectThread.ConnectThread (BluetoothDevice device, UUID uuid)
Public constructor for the ConnectThread class.
Parameters
device BluetoothDevice object
uuid UUID object
Creates a RFCOMM Bluetooth Socket
Definition at line 157 of file MyBluetoothService.java.
                                                                {
            // Use a temporary object that is later assigned to mmSocket because mmSocket is final //
            BluetoothSocket tmp = null;
            mmDevice = device;
            try {
                // Get a BluetoothSocket to connect with the given BluetoothDevice. //
                tmp = device.createRfcommSocketToServiceRecord(uuid);
            } catch (IOException e) {
                Log.e(TAG, "Socket's create() method failed", e);
            }
            mmSocket = tmp;
        }
References com.example.choturemote.MyBluetoothService.mmDevice, com.example.choturemote.MyBluetoothService.ConnectThread.mmSocket, and com.example.choturemote.MyBluetoothService.TAG.
Member Function Documentation
cancel()
void com.example.choturemote.MyBluetoothService.ConnectThread.cancel ()
Closes the socket.
Closes the client socket and causes the thread to finish. Called from the main activity to shut down the connection.
Definition at line 217 of file MyBluetoothService.java.
                             {
            try {
                mmSocket.close();
            } catch (IOException e) {
                Log.e(TAG, "Could not close the client socket", e);
            }
        }
References com.example.choturemote.MyBluetoothService.ConnectThread.mmSocket, and com.example.choturemote.MyBluetoothService.TAG.
Referenced by com.example.choturemote.MyBluetoothService.cancelThreads().
run()
void com.example.choturemote.MyBluetoothService.ConnectThread.run ()
Main code that runs in the Thread.
Try Catch to attempt a connection to the remote device.
Definition at line 175 of file MyBluetoothService.java.
                          {
            // Cancel discovery because it otherwise slows down the connection //
            bluetoothAdapter.cancelDiscovery();
            try {
                // Connect to the remote device through the socket. This call blocks until it succeeds or throws an exception //
                mmSocket.connect();
            } catch (IOException connectException) {
                // Unable to connect; close the socket and return //
                Log.d(TAG, "R.string.CONNECTION_TO_DEVICE_UNSUCCESSFUL");
                showToast(R.string.CONNECTION_TO_DEVICE_UNSUCCESSFUL);
                try {
                    mmSocket.close();
                } catch (IOException closeException) {
                    Log.e(TAG, "Could not close the client socket", closeException);
                }
                // dismiss the progressDialog //
                try {
                    mProgressDialog.dismiss();
                } catch (NullPointerException e) {
                    e.printStackTrace();
                }
                return;
            }
            // The connection attempt succeeded. Perform work associated with the connection in a separate thread. //
            Log.d(TAG, "R.string.CONNECTION_TO_DEVICE_SUCCESSFUL");
            showToast(R.string.CONNECTION_TO_DEVICE_SUCCESSFUL);
            // Start a Thread that'll manage the work associated with the connection //
            connected(mmSocket, mmDevice);
        }
References com.example.choturemote.MyBluetoothService.bluetoothAdapter, com.example.choturemote.MyBluetoothService.connected(), com.example.choturemote.MyBluetoothService.mmDevice, com.example.choturemote.MyBluetoothService.ConnectThread.mmSocket, com.example.choturemote.MyBluetoothService.mProgressDialog, com.example.choturemote.MyBluetoothService.showToast(), and com.example.choturemote.MyBluetoothService.TAG.
Member Data Documentation
mmSocket
final BluetoothSocket com.example.choturemote.MyBluetoothService.ConnectThread.mmSocket [private]
An instance of a Bluetooth socket.
A socket is one endpoint of a two-way communication link
The most common type of Bluetooth socket is RFCOMM, which is the type supported by the Android APIs
Definition at line 149 of file MyBluetoothService.java.
Referenced by com.example.choturemote.MyBluetoothService.ConnectThread.cancel(), com.example.choturemote.MyBluetoothService.ConnectThread.ConnectThread(), and com.example.choturemote.MyBluetoothService.ConnectThread.run().
The documentation for this class was generated from the following file:
MyBluetoothService.java