com.example.choturemote.ui.main.Word Class Reference
Represents a collection of resource IDs.
Public Member Functions
Word (int stringResourceId)
Constructor.
Word (int stringResourceId, int imageResourceId)
Constructor.
int getStringResourceId ()
int getImageResourceId ()
boolean hasImage ()
Private Attributes
int mStringResourceId
int mImageResourceId = NO_IMAGE_PROVIDED
Static Private Attributes
static final int NO_IMAGE_PROVIDED = -1
Detailed Description
Represents a collection of resource IDs.
It contains resource IDs for Strings and optional Images
Definition at line 29 of file Word.java.
Constructor & Destructor Documentation
Word() [1/2]
com.example.choturemote.ui.main.Word.Word (int stringResourceId)
Constructor.
A constructor that only takes in a String resourceID. Not used. Kept for later use.
Parameters
stringResourceId is the string resource ID for the text associated with a Word
Definition at line 45 of file Word.java.
                                      {
        mStringResourceId = stringResourceId;
    }
References com.example.choturemote.ui.main.Word.mStringResourceId.
Word() [2/2]
com.example.choturemote.ui.main.Word.Word (int stringResourceId, int imageResourceId)
Constructor.
A constructor that only takes in a String resourceID and an Image resourceId
Parameters
stringResourceId is the string resource ID for the text associated with a Word
imageResourceId is the drawable resource ID for the image associated with the Word
Definition at line 56 of file Word.java.
                                                           {
        mStringResourceId = stringResourceId;
        mImageResourceId = imageResourceId;
    }
References com.example.choturemote.ui.main.Word.mImageResourceId, and com.example.choturemote.ui.main.Word.mStringResourceId.
Member Function Documentation
getImageResourceId()
int com.example.choturemote.ui.main.Word.getImageResourceId ()
Get the image resource ID for the image associated with the Word
Returns
integer Resource ID
Definition at line 74 of file Word.java.
                                    {
        return mImageResourceId;
    }
References com.example.choturemote.ui.main.Word.mImageResourceId.
Referenced by com.example.choturemote.ui.main.ExpressionsWordAdapter.getView(), and com.example.choturemote.ui.main.LocomotionWordAdapter.getView().
getStringResourceId()
int com.example.choturemote.ui.main.Word.getStringResourceId ()
Get the string resource ID for the text associated with the Word
Returns
integer Resource ID
Definition at line 65 of file Word.java.
                                     {
        return mStringResourceId;
    }
References com.example.choturemote.ui.main.Word.mStringResourceId.
Referenced by com.example.choturemote.ui.main.ExpressionsWordAdapter.getView(), com.example.choturemote.ui.main.ExpressionsFragment.onCreateView(), and com.example.choturemote.ui.main.SpeakingFragment.onCreateView().
hasImage()
boolean com.example.choturemote.ui.main.Word.hasImage ()
Returns whether or not there is an image for this word.
Returns
boolean TRUE or FALSE
Definition at line 82 of file Word.java.
                              {
        return mImageResourceId != NO_IMAGE_PROVIDED;
    }
References com.example.choturemote.ui.main.Word.mImageResourceId, and com.example.choturemote.ui.main.Word.NO_IMAGE_PROVIDED.
Referenced by com.example.choturemote.ui.main.ExpressionsWordAdapter.getView(), and com.example.choturemote.ui.main.LocomotionWordAdapter.getView().
Member Data Documentation
mImageResourceId
int com.example.choturemote.ui.main.Word.mImageResourceId = NO_IMAGE_PROVIDED [private]
Optional image resource ID for the image associated with a Word
Definition at line 35 of file Word.java.
Referenced by com.example.choturemote.ui.main.Word.getImageResourceId(), com.example.choturemote.ui.main.Word.hasImage(), and com.example.choturemote.ui.main.Word.Word().
mStringResourceId
int com.example.choturemote.ui.main.Word.mStringResourceId [private]
String resource ID for the text associated with a Word
Definition at line 32 of file Word.java.
Referenced by com.example.choturemote.ui.main.Word.getStringResourceId(), and com.example.choturemote.ui.main.Word.Word().
NO_IMAGE_PROVIDED
final int com.example.choturemote.ui.main.Word.NO_IMAGE_PROVIDED = -1 [static], [private]
Constant value that represents no image was provided for this word
Definition at line 38 of file Word.java.
Referenced by com.example.choturemote.ui.main.Word.hasImage().
The documentation for this class was generated from the following file:
Word.java