com.example.choturemote.MainActivity Class Reference
This is where everything important happens.
Public Member Functions
void showToastMethod (final String message)
Toasts for threads other than the main.
Static Public Member Functions
static void writeToBluetooth (String classifier, String instruction, String modifier)
Forms and sends command Strings through Bluetooth.
Static Public Attributes
static MyBluetoothService myBluetoothService
Handles Bluetooth stuff.
Protected Member Functions
void onCreate (Bundle savedInstanceState)
fires when the system first creates the activity.
void onDestroy ()
The final call you receive before your activity is destroyed.
void onActivityResult (int requestCode, int resultCode, @Nullable Intent data)
Called back after focus is returned from process started by startActivityForResult()
Static Package Attributes
static final UUID MY_UUID = UUID.fromString(`00001101-0000-1000-8000-00805F9B34FB`)
Universally Unique Identifier (UUID)
static String TERMINATOR
Command instruction terminator.
static String DISABLE
Private Member Functions
void beginConnection ()
Establishes a Bluetooth serial communication.
Private Attributes
final boolean TESTING = false
Debugging tool.
SectionsPagerAdapter sectionsPagerAdapter
Custom class.
TabLayout tabs
TabLayout provides a horizontal layout to display tabs.
ViewPager viewPager
Layout manager allowing left/right swipes to get access to more options.
String MAC_ADDRESS
BluetoothAdapter bluetoothAdapter
A BluetoothAdapter object.
int REQUEST_ENABLE_BT = 1
An integer passed to startActivityForResult() and received by onActivityResult(). If it is greater >= 0, this code will be returned in onActivityResult() when the activity exits. Does nothing of significance at present.
final BroadcastReceiver mBTStateBroadcastReceiver
a BroadcastReceiver type object
Static Private Attributes
static String POKE_SLEEP_CLASSIFIER
Used to send sleep or poke instructions.
static String SEPARATOR
Command instruction separator.
static String POKE
Used as a modifier.
static String ENABLE
static String TAG = `MainActivity`
Detailed Description
This is where everything important happens.
This is the first screen to appear when the user launches the app. This handles everything and calls everything.
Definition at line 35 of file MainActivity.java.
Member Function Documentation
beginConnection()
void com.example.choturemote.MainActivity.beginConnection () [private]
Establishes a Bluetooth serial communication.
Fetches device info from paired devices.
Definition at line 281 of file MainActivity.java.
                                   {
        boolean deviceFound = false;
        Set<BluetoothDevice> pairedDevices = bluetoothAdapter.getBondedDevices();
        if (pairedDevices.size() > 0) {
            // There are paired devices. Get the name and address of each paired device. //
            for (BluetoothDevice device : pairedDevices) {
                String deviceHardwareAddress = device.getAddress(); // MAC address
                if (deviceHardwareAddress.equals(MAC_ADDRESS)) {
                    // This bit matches the MAC address of your "face device" to a paired device's //
                    // Then establishes a connection on a separate thread //
                    deviceFound = true;
                    myBluetoothService.startClient(device, MY_UUID);
                    break;
                }
            }
            if (!deviceFound) {
                Toast.makeText(getBaseContext(), "ERROR: Device with MAC address " + MAC_ADDRESS + " not paired", Toast.LENGTH_LONG).show();
                this.finishAffinity();
            }
        } else {
            Toast.makeText(getBaseContext(), "ERROR:" + getString(R.string.NO_PAIRED_DEVICES), Toast.LENGTH_LONG).show();
            this.finishAffinity();
        }
    }
References com.example.choturemote.MainActivity.bluetoothAdapter, com.example.choturemote.MainActivity.MAC_ADDRESS, com.example.choturemote.MainActivity.MY_UUID, com.example.choturemote.MainActivity.myBluetoothService, and com.example.choturemote.MyBluetoothService.startClient().
Referenced by com.example.choturemote.MainActivity.onActivityResult(), and com.example.choturemote.MainActivity.onCreate().
onActivityResult()
void com.example.choturemote.MainActivity.onActivityResult (int requestCode, int resultCode, @Nullable Intent data) [protected]
Called back after focus is returned from process started by startActivityForResult()
Parameters
requestCode the requestCode passed as the second parameter to startActivityForResult(), here it is REQUEST_ENABLE_BT
resultCode Possible values - RESULT_OK or RESULT_CANCELED
data Optional parameter. An Intent, which can return result data to the caller. @Nullable denotes that a value can be null.
If enabling Bluetooth succeeds, this activity receives the RESULT_OK result code in the onActivityResult() callback. If Bluetooth was not enabled due to an error (or the user responded `No`) then the result code is RESULT_CANCELED.
Definition at line 336 of file MainActivity.java.
                                                                                            {
        if (requestCode == REQUEST_ENABLE_BT && resultCode == RESULT_OK) {
            beginConnection();
        }
        if (resultCode == RESULT_CANCELED)
            Toast.makeText(this, "Unable to access Bluetooth", Toast.LENGTH_SHORT).show();
    }
References com.example.choturemote.MainActivity.beginConnection(), and com.example.choturemote.MainActivity.REQUEST_ENABLE_BT.
onCreate()
void com.example.choturemote.MainActivity.onCreate (Bundle savedInstanceState) [protected]
fires when the system first creates the activity.
Parameters
savedInstanceState A Bundle object containing the activity's previously saved state. If the activity has never existed before, the value of the Bundle object is null. (Bundle is generally used for passing data between various activities of android.)
In the onCreate() method, you perform basic application startup logic that should happen only once for the entire life of the activity.
Definition at line 166 of file MainActivity.java.
                                                       {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        // String code //
        POKE_SLEEP_CLASSIFIER = getString(R.string.POKE_SLEEP_CLASSIFIER);
        SEPARATOR = getString(R.string.SEPARATOR);
        TERMINATOR = getString(R.string.TERMINATOR);
        POKE = getString(R.string.POKE_INSTRUCTION);
        DISABLE = getString(R.string.DISABLE);
        ENABLE = getString(R.string.ENABLE);
        // ViewPager and connected TabLayout setup //
        sectionsPagerAdapter = new SectionsPagerAdapter(this, getSupportFragmentManager());
        viewPager = findViewById(R.id.view_pager);
        viewPager.setAdapter(sectionsPagerAdapter);
        tabs = findViewById(R.id.tabs);
        tabs.setupWithViewPager(viewPager);
        // FAB //
        final FloatingActionButton fab = findViewById(R.id.fab);
        fab.setOnClickListener(new View.OnClickListener() {
            boolean toggle = true;
            @Override
            public void onClick(View view) {
                // Toggles between POKE ENABLED and POKE DISABLED //
                toggle = !toggle;
                if (toggle) {
                    // Changes the FAB icon //
                    fab.setImageDrawable(ContextCompat.getDrawable(getApplicationContext(), android.R.drawable.ic_menu_view));
                    writeToBluetooth(POKE_SLEEP_CLASSIFIER, POKE, ENABLE);
                    Snackbar.make(view, POKE + " " + ENABLE + "ED", Snackbar.LENGTH_LONG)
                            .setAction("Action", null).show();
                } else {
                    fab.setImageDrawable(ContextCompat.getDrawable(getApplicationContext(), android.R.drawable.ic_lock_idle_lock));
                    writeToBluetooth(POKE_SLEEP_CLASSIFIER, POKE, DISABLE);
                    Snackbar.make(view, POKE + " " + DISABLE + "ED", Snackbar.LENGTH_LONG)
                            .setAction("Action", null).show();
                }
            }
        });
        fab.setOnLongClickListener(new View.OnLongClickListener() {
            @Override
            public boolean onLongClick(View view) {
                // Triggers sleep animation and turns off screen of the "face device" //
                writeToBluetooth(POKE_SLEEP_CLASSIFIER, "SLEEP", "000");
                Snackbar.make(view, "Chotu is now asleep", Snackbar.LENGTH_LONG)
                        .setAction("Action", null).show();
                return true;
            }
        });
        //Bluetooth code //
        if (TESTING)
            MAC_ADDRESS = getString(R.string.TESTING_MAC_ADDRESS_2); // MAC_ADDRESS IN USE - EASIER TO CHANGE HERE THAN ALL OVER THE PLACE //
        else
            MAC_ADDRESS = getString(R.string.MAC_ADDRESS); // MAC_ADDRESS IN USE - EASIER TO CHANGE HERE THAN ALL OVER THE PLACE //
        myBluetoothService = new MyBluetoothService(MainActivity.this) {
            @Override
            public void showToast(int resourceID) {
                // Will receive a resourceID, convert it into a String, and send it to showToastMethod() //
                showToastMethod(getString(resourceID));
            }
        };
        // Get a handle/reference to the default local Bluetooth adapter of the device being used //
        bluetoothAdapter = BluetoothAdapter.getDefaultAdapter();
        if (bluetoothAdapter == null)
            Toast.makeText(this, "Error: This device device does not support Bluetooth", Toast.LENGTH_LONG).show();
        else {
            if (!bluetoothAdapter.isEnabled()) {
                // Creating an Intent //
                Intent enableBtIntent = new Intent(BluetoothAdapter.ACTION_REQUEST_ENABLE);
                // A dialog appears requesting user permission to enable Bluetooth. //
                // If the user responds "Yes", the system begins to enable Bluetooth //
                // Focus returns to your application once the process completes (or fails) //
                // onActivityResult() that gets called upon return of focus //
                startActivityForResult(enableBtIntent, REQUEST_ENABLE_BT);
            } else {
                beginConnection();
            }
            // Informs us when BT condition changes //
            // Registers a BroadcastReceiver to be run in the main activity thread. //
            // The receiver will be called with any broadcast Intent that matches filter //
            // The Broadcast Receiver implementation is outside onCreate() //
            registerReceiver(mBTStateBroadcastReceiver, new IntentFilter(BluetoothAdapter.ACTION_STATE_CHANGED));
        }
    }
References com.example.choturemote.MainActivity.beginConnection(), com.example.choturemote.MainActivity.bluetoothAdapter, com.example.choturemote.MainActivity.DISABLE, com.example.choturemote.MainActivity.ENABLE, com.example.choturemote.MainActivity.MAC_ADDRESS, com.example.choturemote.MainActivity.mBTStateBroadcastReceiver, com.example.choturemote.MainActivity.myBluetoothService, com.example.choturemote.MainActivity.POKE, com.example.choturemote.MainActivity.POKE_SLEEP_CLASSIFIER, com.example.choturemote.MainActivity.REQUEST_ENABLE_BT, com.example.choturemote.MainActivity.sectionsPagerAdapter, com.example.choturemote.MainActivity.SEPARATOR, com.example.choturemote.MainActivity.showToastMethod(), com.example.choturemote.MainActivity.tabs, com.example.choturemote.MainActivity.TERMINATOR, com.example.choturemote.MainActivity.TESTING, com.example.choturemote.MainActivity.viewPager, and com.example.choturemote.MainActivity.writeToBluetooth().
onDestroy()
void com.example.choturemote.MainActivity.onDestroy () [protected]
The final call you receive before your activity is destroyed.
This opportunity is used to unregister the BroadcastReceiver, mBTStateBroadcastReceiver
Definition at line 269 of file MainActivity.java.
                               {
        super.onDestroy();
        // Unregistering broadcast listener to free up resources
        unregisterReceiver(mBTStateBroadcastReceiver);
    }
References com.example.choturemote.MainActivity.mBTStateBroadcastReceiver.
showToastMethod()
void com.example.choturemote.MainActivity.showToastMethod (final String message)
Toasts for threads other than the main.
Parameters
message Message to be shown in Toast
Toasts can only be displayed on the main thread. To call Toasts from other threads, a public method in the Activity running on the main thread can be used.
Definition at line 349 of file MainActivity.java.
                                                      {
        runOnUiThread(new Runnable() {
            public void run() {
                Toast.makeText(getBaseContext(), message, Toast.LENGTH_SHORT).show();
            }
        });
    }
Referenced by com.example.choturemote.MainActivity.onCreate().
writeToBluetooth()
static void com.example.choturemote.MainActivity.writeToBluetooth (String classifier, String instruction, String modifier) [static]
Forms and sends command Strings through Bluetooth.
Parameters
classifier Possible values F, B, R, L, E, etc.
instruction Parameterizes or explains the classifier. This can be a number or can be something else entirely.
modifier Modifies the parameter definition.
Constructs command Strings using SEPARATOR and TERMINATOR then sends command String through Bluetooth. This makes the command construction process easily programmable and editable as it is all in one place.
Definition at line 316 of file MainActivity.java.
                                                                                                {
        if (MyBluetoothService.connectedThreadRunning()) {
            String fullMessage = classifier + SEPARATOR + instruction + SEPARATOR + modifier + TERMINATOR;
            // Converts the String to an Array of byte type //
            byte[] bytes = fullMessage.getBytes(Charset.defaultCharset());
            myBluetoothService.write(bytes);
        }
    }
References com.example.choturemote.MyBluetoothService.connectedThreadRunning(), com.example.choturemote.MainActivity.myBluetoothService, com.example.choturemote.MainActivity.SEPARATOR, com.example.choturemote.MainActivity.TERMINATOR, and com.example.choturemote.MyBluetoothService.write().
Referenced by com.example.choturemote.MainActivity.onCreate(), com.example.choturemote.ui.main.LocomotionFragment.onCreateView(), com.example.choturemote.ui.main.ExpressionsFragment.onCreateView(), and com.example.choturemote.ui.main.SpeakingFragment.onCreateView().
Member Data Documentation
bluetoothAdapter
BluetoothAdapter com.example.choturemote.MainActivity.bluetoothAdapter [private]
A BluetoothAdapter object.
A BluetoothAdapter lets you perform fundamental Bluetooth tasks, such as initiate device discovery, query a list of bonded (paired) devices, instantiate a BluetoothDevice using a known MAC address, and create a BluetoothServerSocket to listen for connection requests from other devices, and start a scan for Bluetooth LE devices.
Definition at line 121 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.beginConnection(), and com.example.choturemote.MainActivity.onCreate().
DISABLE
com.example.choturemote.MainActivity.DISABLE [static], [package]
Disables poking
Definition at line 104 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
ENABLE
com.example.choturemote.MainActivity.ENABLE [static], [private]
Enables poking
Definition at line 104 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
MAC_ADDRESS
String com.example.choturemote.MainActivity.MAC_ADDRESS [private]
MAC ADDRESS of the Bluetooth device to establish communication with
Definition at line 115 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.beginConnection(), and com.example.choturemote.MainActivity.onCreate().
mBTStateBroadcastReceiver
final BroadcastReceiver com.example.choturemote.MainActivity.mBTStateBroadcastReceiver [private]
Initial value:
= new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            
            final String action = intent.getAction();
            if (action.equals(BluetoothAdapter.ACTION_STATE_CHANGED)) {
                final int state = intent.getIntExtra(BluetoothAdapter.EXTRA_STATE, BluetoothAdapter.ERROR);
                switch (state) {
                    case BluetoothAdapter.STATE_OFF:
                        Toast.makeText(context, R.string.BT_STATE_OFF_TEXT, Toast.LENGTH_SHORT).show();
                        break;
                    case BluetoothAdapter.STATE_TURNING_OFF:
                        Toast.makeText(context, R.string.BT_STATE_TURNING_OFF_TEXT, Toast.LENGTH_SHORT).show();
                        break;
                    case BluetoothAdapter.STATE_ON:
                        Toast.makeText(context, R.string.BT_STATE_ON_TEXT, Toast.LENGTH_SHORT).show();
                        break;
                    case BluetoothAdapter.STATE_TURNING_ON:
                        Toast.makeText(context, R.string.BT_STATE_TURNING_ON_TEXT, Toast.LENGTH_SHORT).show();
                        break;
                }
            }
        }
    }
a BroadcastReceiver type object
Receives and handles broadcast intents sent by Context.sendBroadcast(Intent).
This is an implementation of BroadcastReceiver registered to be run in the main activity thread. Its receiver is called with any broadcast Intent that matches filter, in this case is BluetoothAdapter.ACTION_STATE_CHANGED (in other words, when the state of the local Bluetooth adapter has been changed).
Definition at line 134 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate(), and com.example.choturemote.MainActivity.onDestroy().
MY_UUID
final UUID com.example.choturemote.MainActivity.MY_UUID = UUID.fromString(`00001101-0000-1000-8000-00805F9B34FB`) [static], [package]
Universally Unique Identifier (UUID)
Creating a UUID which represents a 128-bit value.
More information on UUIDs by the Internet Engineering Task Force can be found here.
UUIDs are not tied to particular devices. They identify software services. You just need both sides to use the same one.
`00001101-0000-1000-8000-00805F9B34FB` is the one and only UUID for SPP (serial port profile). Check out the Android Developer's page.
Definition at line 51 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.beginConnection().
myBluetoothService
MyBluetoothService com.example.choturemote.MainActivity.myBluetoothService [static]
Handles Bluetooth stuff.
Custom class. Handles Bluetooth stuff.
Definition at line 57 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.beginConnection(), com.example.choturemote.MainActivity.onCreate(), and com.example.choturemote.MainActivity.writeToBluetooth().
POKE
com.example.choturemote.MainActivity.POKE [static], [private]
Used as a modifier.
Used as a modifier to distinguish a poke command from a sleep command.
Definition at line 103 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
POKE_SLEEP_CLASSIFIER
com.example.choturemote.MainActivity.POKE_SLEEP_CLASSIFIER [static], [private]
Used to send sleep or poke instructions.
Command Strings pertaining to sleep or poke instructions classified by this classifier
Definition at line 101 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
REQUEST_ENABLE_BT
int com.example.choturemote.MainActivity.REQUEST_ENABLE_BT = 1 [private]
An integer passed to startActivityForResult() and received by onActivityResult(). If it is greater >= 0, this code will be returned in onActivityResult() when the activity exits. Does nothing of significance at present.
Definition at line 126 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onActivityResult(), and com.example.choturemote.MainActivity.onCreate().
sectionsPagerAdapter
SectionsPagerAdapter com.example.choturemote.MainActivity.sectionsPagerAdapter [private]
Custom class.
SectionsPagerAdapter extends FragmentPagerAdapter which is an implementation of the PagerAdapter class. It is needed for the ViewPager object, viewPager.
Definition at line 63 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
SEPARATOR
com.example.choturemote.MainActivity.SEPARATOR [static], [private]
Command instruction separator.
Is used to visually distinguish between parts of a String instruction.
Definition at line 102 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate(), and com.example.choturemote.MainActivity.writeToBluetooth().
tabs
TabLayout com.example.choturemote.MainActivity.tabs [private]
TabLayout provides a horizontal layout to display tabs.
The class method setupWithViewPager() links the given ViewPager and this TabLayout together so that changes in one are automatically reflected in the other. This includes scroll state changes and clicks. The tabs displayed in this layout will be populated from the ViewPager adapter's page titles.
The TabLayout object, tabs, is a View in the activity_main.xml layout file with the id `tabs`.
Definition at line 71 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
TAG
String com.example.choturemote.MainActivity.TAG = `MainActivity` [static], [private]
Debugging tool
Definition at line 109 of file MainActivity.java.
TERMINATOR
com.example.choturemote.MainActivity.TERMINATOR [static], [package]
Command instruction terminator.
Used to indicate the end of a String instruction.
Definition at line 102 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate(), and com.example.choturemote.MainActivity.writeToBluetooth().
TESTING
final boolean com.example.choturemote.MainActivity.TESTING = false [private]
Debugging tool.
Toggle to FALSE when using it with the two HC-05's on a breadboard. Check their MAC Addresses before using.
Definition at line 41 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
viewPager
ViewPager com.example.choturemote.MainActivity.viewPager [private]
Layout manager allowing left/right swipes to get access to more options.
ViewPager is a layout manager that allows the user to flip left and right through pages of data.
You supply an implementation of a PagerAdapter to generate the pages that the view shows. In this case it was supplied a SectionsPagerAdapter object sectionsPagerAdapter. SectionsPagerAdapter extends FragmentPagerAdapter which is an implementation of the PagerAdapter class.
More information at the ViewPager entry and PagerAdapter entry in the Android Developer's documentation.
The ViewPager object, viewPager, is a View in the activity_main.xml layout file with the id `view_pager`.
Definition at line 81 of file MainActivity.java.
Referenced by com.example.choturemote.MainActivity.onCreate().
The documentation for this class was generated from the following file:
MainActivity.java