com.example.choturemote.ui.main.ExpressionsWordAdapter Class Reference
An ArrayAdapter Implementation.
Public Member Functions
ExpressionsWordAdapter (Context context, ArrayList< Word > words, int colorResourceId)
Constructor.
View getView (int position, View convertView, ViewGroup parent)
Return a View object.
Private Attributes
int mColorResourceId
Detailed Description
An ArrayAdapter Implementation.
This is an ArrayAdapter used to provide views for the AdapterView
Returns a view for each object in a collection of Word objects provided
Definition at line 43 of file ExpressionsWordAdapter.java.
Constructor & Destructor Documentation
ExpressionsWordAdapter()
com.example.choturemote.ui.main.ExpressionsWordAdapter.ExpressionsWordAdapter (Context context, ArrayList< Word > words, int colorResourceId)
Constructor.
Constructor for an ExpressionsWordAdapter object.
Parameters
context the current context (i.e. Activity) that the adapter is being created in
words the list of Word objects to be displayed
colorResourceId the resource ID for the background color for this list of words
Definition at line 58 of file ExpressionsWordAdapter.java.
                                                                                               {
        super(context, 0, words);
        mColorResourceId = colorResourceId;
    }
References com.example.choturemote.ui.main.ExpressionsWordAdapter.mColorResourceId.
Member Function Documentation
getView()
View com.example.choturemote.ui.main.ExpressionsWordAdapter.getView (int position, View convertView, ViewGroup parent)
Return a View object.
Parameters
position specified position in the data set of the Word to be displayed
convertView a View type. Here value is null. Instead expressions_grid_item.xml is inflated to create the View
parent Parent View object of the View object being returned
Returns
a View that displays the data at the specified position in the data set
Check if an existing view is being reused, otherwise inflate the view
getView() was @Override in order to return a custom type View
Called back automatically by Android
Definition at line 75 of file ExpressionsWordAdapter.java.
                                                                          {
        View itemView = convertView;
        if (itemView == null) {
            // Inflating expressions_grid_item.xml //
            itemView = LayoutInflater.from(getContext()).inflate(
                    R.layout.expressions_grid_item, parent, false);
        }
        // Get the Word object located at this position in the list //
        Word currentWord = getItem(position);
        // Find the TextView in the expressions_grid_item.xml layout with the ID "default_text_view" //
        TextView defaultTextView = (TextView) itemView.findViewById(R.id.default_text_view);
        // Get the text from the currentWord object and set this text on the default TextView //
        defaultTextView.setText(currentWord.getStringResourceId());
        // Find the ImageView in the expressions_grid_item.xml layout with the ID "image" //
        ImageView imageView = (ImageView) itemView.findViewById(R.id.image);
        if (currentWord.hasImage()) {
            // If an image is available, display the provided image based on the resource ID //
            imageView.setImageResource(currentWord.getImageResourceId());
            // Make sure the view is visible //
            imageView.setVisibility(View.VISIBLE);
        } else {
            // Otherwise hide the ImageView (set visibility to GONE) //
            imageView.setVisibility(View.GONE);
        }
        // Set the background color of the text container View //
        View textContainer = itemView.findViewById(R.id.text_container);
        int color = ContextCompat.getColor(getContext(), mColorResourceId); // Find the color that the resource ID maps to //
        textContainer.setBackgroundColor(color);
        // Return the itemView object(containing one TextView and one ImageView) so that it can be shown in the GridView //
        return itemView;
    }
References com.example.choturemote.ui.main.Word.getImageResourceId(), com.example.choturemote.ui.main.Word.getStringResourceId(), com.example.choturemote.ui.main.Word.hasImage(), and com.example.choturemote.ui.main.ExpressionsWordAdapter.mColorResourceId.
Member Data Documentation
mColorResourceId
int com.example.choturemote.ui.main.ExpressionsWordAdapter.mColorResourceId [private]
Resource ID for the background color for this list of Word objects
Definition at line 48 of file ExpressionsWordAdapter.java.
Referenced by com.example.choturemote.ui.main.ExpressionsWordAdapter.ExpressionsWordAdapter(), and com.example.choturemote.ui.main.ExpressionsWordAdapter.getView().
The documentation for this class was generated from the following file:
ExpressionsWordAdapter.java